const router = require('express').Router();
const ctrl = require('../controllers/cours.controller');
const { authenticate, requireAdmin } = require('../middleware/auth');
router.get('/', ctrl.getAll);
router.post('/', authenticate, requireAdmin, ctrl.create);
router.put('/:id', authenticate, requireAdmin, ctrl.update);
router.delete('/:id', authenticate, requireAdmin, ctrl.remove);
router.post('/reserver', authenticate, ctrl.reserver);
router.put('/reservation/:id/annuler', authenticate, ctrl.annulerReservation);
router.get('/mes-reservations', authenticate, ctrl.getMesReservations);
module.exports = router;
